# Generated by Django 4.2.1 on 2023-05-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_player_id_alter_player_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user',
        ),
    ]
