# Generated by Django 4.2.1 on 2023-05-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_username_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daylies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
                ('series', models.IntegerField()),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
