# Generated by Django 4.2.1 on 2023-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_daylies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylies',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
