# Generated by Django 4.2.1 on 2023-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_daylies_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylies',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
